### ISSUE TITLE
WASM Add on screen touch controls

### ISSUE THREAD

**Issue by pfiaux** [neophob/ganother-world#33]
For the wasm version it would be cool to add some html buttons which are mapped to the keys, this would allow playing on a touch screen (mobile, tablet). Could be on the side of the screen or overlayed.

**Comment by neophob** [comment]
@pfiaux do you want to take over this issue?

**Comment by pfiaux** [comment]
I'll find some time for it.
What do you think design wise tho? use transparency and show on top of the canvas?

**Comment by neophob** [comment]
that would my my first idea as well. i guess other games use similar techniques

**Comment by pfiaux** [comment]
Note: `chokidar "wasm/*.html" "wasm/*.js" "**/*.go" -c "make build-wasm"` saves having to build all the tim (`npm install -g chokidar-cli`). Still need to refresh the browser tho but, one step at a time :)
